/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTreasuryRouteImport } from './routes/_authenticated/admin.treasury'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin.stock'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRentRouteImport } from './routes/_authenticated/admin.rent'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCreditsRouteImport } from './routes/_authenticated/admin.credits'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as ApiPublicWebhooksShwaryRouteImport } from './routes/api/public/webhooks/shwary'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTreasuryRoute =
  AuthenticatedAdminTreasuryRouteImport.update({
    id: '/treasury',
    path: '/treasury',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRentRoute = AuthenticatedAdminRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCreditsRoute =
  AuthenticatedAdminCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksShwaryRoute = ApiPublicWebhooksShwaryRouteImport.update({
  id: '/api/public/webhooks/shwary',
  path: '/api/public/webhooks/shwary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rent': typeof AuthenticatedAdminRentRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/treasury': typeof AuthenticatedAdminTreasuryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/shwary': typeof ApiPublicWebhooksShwaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rent': typeof AuthenticatedAdminRentRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/treasury': typeof AuthenticatedAdminTreasuryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/shwary': typeof ApiPublicWebhooksShwaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/rent': typeof AuthenticatedAdminRentRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/treasury': typeof AuthenticatedAdminTreasuryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/shwary': typeof ApiPublicWebhooksShwaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boutique'
    | '/compte'
    | '/sitemap.xml'
    | '/admin'
    | '/produit/$slug'
    | '/admin/activity'
    | '/admin/credits'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/expenses'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/rent'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/team'
    | '/admin/treasury'
    | '/admin/'
    | '/api/public/webhooks/shwary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/boutique'
    | '/compte'
    | '/sitemap.xml'
    | '/produit/$slug'
    | '/admin/activity'
    | '/admin/credits'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/expenses'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/rent'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/team'
    | '/admin/treasury'
    | '/admin'
    | '/api/public/webhooks/shwary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/boutique'
    | '/compte'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/produit/$slug'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/credits'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/rent'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/treasury'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/shwary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CompteRoute: typeof CompteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiPublicWebhooksShwaryRoute: typeof ApiPublicWebhooksShwaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/treasury': {
      id: '/_authenticated/admin/treasury'
      path: '/treasury'
      fullPath: '/admin/treasury'
      preLoaderRoute: typeof AuthenticatedAdminTreasuryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rent': {
      id: '/_authenticated/admin/rent'
      path: '/rent'
      fullPath: '/admin/rent'
      preLoaderRoute: typeof AuthenticatedAdminRentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/credits': {
      id: '/_authenticated/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AuthenticatedAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/shwary': {
      id: '/api/public/webhooks/shwary'
      path: '/api/public/webhooks/shwary'
      fullPath: '/api/public/webhooks/shwary'
      preLoaderRoute: typeof ApiPublicWebhooksShwaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminCreditsRoute: typeof AuthenticatedAdminCreditsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRentRoute: typeof AuthenticatedAdminRentRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTreasuryRoute: typeof AuthenticatedAdminTreasuryRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminCreditsRoute: AuthenticatedAdminCreditsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRentRoute: AuthenticatedAdminRentRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminTreasuryRoute: AuthenticatedAdminTreasuryRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BoutiqueRoute: BoutiqueRoute,
  CompteRoute: CompteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiPublicWebhooksShwaryRoute: ApiPublicWebhooksShwaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
